name: Build
on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - ".idea/**"
      - ".vscode/**"
      - "LICENSE"
      - "*.md"
      - "commitlint.config.cjs"
      - "lefthook.yaml"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - ".idea/**"
      - ".vscode/**"
      - ".npmignore"
      - "LICENSE"
      - "*.md"
      - "commitlint.config.cjs"
      - "lefthook.yaml"
      - "package.json"
      - "pnpm-lock.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.24", "1.25"]

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go get -v -t

      - name: Generate
        run: go generate -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test
